[package]
name = "should-be-public"
version = "0.0.0-AFTER"
edition = "2021"
publish = false

[dependencies]
rustdoc-json = "0.9"
serde_json = "1.0"
rustdoc-types = "0.32"
color-eyre = "0.6"

[dependencies.clap]
version = "4.5"
features = ["derive"]
